Smartling/java-api-sdk

pom.xml

Enable JavaDoc customization and links to 3rd party libraries.

docs: add JavaDoc configuration

---

smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/util/FileUploadClientFactory.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/util/FileUploadProxyUtils.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/FileUploadProxy.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/JobBatchesApi.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/JobBatchesApiFactory.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/pto/BatchActionRequestPTO.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/pto/BatchItemLocalePTO.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/pto/BatchItemPTO.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/pto/BatchPTO.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/pto/BatchStatusResponsePTO.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/pto/CreateBatchRequestPTO.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/pto/CreateBatchResponsePTO.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/pto/FileUploadPTO.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/pto/SearchParamsPTO.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/pto/StreamFileUploadPTO.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/pto/WorkflowPTO.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/FileUploadProxy.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/JobBatchesApi.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/JobBatchesApiFactory.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/pto/SearchParamsPTO.java
smartling-job-batches-api/src/test/java/com/smartling/api/jobbatches/v1/JobBatchesApiTest.java

Quick background
v1 and v2 use different approaches
v1 requires synchronous files upload, with finalizing batch "execution" after all uploads, 
v2 - asynchronous, with automatic "execution", requires knowing the number of files to be uploaded at the time of batch creation.
We support v1 because not all integrations can use v2, one of our connectors can't

feat: Job Batches API v1

---

smartling-api-commons/src/main/java/com/smartling/api/v2/authentication/AuthenticationApiFactory.java
smartling-api-commons/src/main/java/com/smartling/api/v2/client/AbstractApiFactory.java
smartling-api-commons/src/test/java/com/smartling/api/v2/AuthenticationApiFactoryTest.java
smartling-api-commons/src/test/java/com/smartling/api/v2/client/AbstractApiFactoryTest.java
smartling-api-sdk-all/src/main/java/com/smartling/api/sdk/SmartlingApiFactory.java
smartling-api-sdk-all/src/main/java/com/smartling/api/sdk/SmartlingApiImpl.java
smartling-issues-api/src/main/java/com/smartling/api/issues/v2/IssuesApiFactory.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/JobBatchesApiFactory.java
smartling-jobs-api/src/main/java/com/smartling/api/jobs/v3/TranslationJobsApiFactory.java
smartling-locales-api/src/main/java/com/smartling/api/locales/v2/LocalesApiFactory.java

Allow developers to provide a custom client factory implementation.
[JIRA Ticket](https://bt.smartling.net/browse/AUT-596)

feat: make client factory customizable

---

smartling-api-commons/src/main/java/com/smartling/api/v2/authentication/AuthenticationApiFactory.java

It is impossible to create a BearerAuthSecretFilter for staging
As we can pass a ClientConfiguration to the builder only with a custom AuthSecretFilter then we should be also able to create this filter with a custom ClientConfiguration

Fix auth on stg

---

pom.xml
smartling-api-commons/src/main/java/com/smartling/api/v2/client/exception/DefaultRestApiExceptionMapper.java
smartling-api-commons/src/main/java/com/smartling/api/v2/client/exception/RestApiExceptionHandler.java
smartling-api-commons/src/test/java/com/smartling/api/v2/auth/AuthenticationIntegrationTest.java
smartling-api-commons/src/test/java/com/smartling/api/v2/auth/DummyApi.java
smartling-api-commons/src/test/java/com/smartling/api/v2/client/exception/DefaultRestApiExceptionMapperTest.java
smartling-api-commons/src/test/java/com/smartling/api/v2/client/exception/RestApiExceptionHandlerTest.java
smartling-api-commons/src/test/java/com/smartling/api/v2/wiremock/SmartlingWireMock.java
smartling-files-api/pom.xml
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/exceptions/JobBatchesApiExceptionMapper.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/exceptions/NoSourceStringsFoundException.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/util/FileUploadProxyUtils.java
smartling-job-batches-api/src/test/java/com/smartling/api/jobbatches/exceptions/JobBatchesApiExceptionMapperTest.java

Exception handler shouldn't rewrap exceptions thrown by Authentication process
[CON-612](https://bt.smartling.net/browse/CON-612)

fix: don't rewrap auth errors

---

smartling-api-commons/src/main/java/com/smartling/api/v2/client/unmarshal/RestApiResponseReaderInterceptor.java
smartling-api-commons/src/test/java/com/smartling/api/v2/client/unmarshal/RestApiResponseReaderInterceptorTest.java
smartling-files-api/src/test/java/com/smartling/api/files/v2/FilesApiIntTest.java

SDK tries to deserialize downloaded file if it is returned as an `application/json`

fix: Omit parsing responses declared as InputStream

---

.github/CODEOWNERS
pom.xml
smartling-api-sdk-all/pom.xml
smartling-strings-api/pom.xml
smartling-strings-api/src/main/java/com/smartling/api/strings/v2/StringsApi.java
smartling-strings-api/src/main/java/com/smartling/api/strings/v2/StringsApiFactory.java
smartling-strings-api/src/main/java/com/smartling/api/strings/v2/pto/AsyncStatusResponsePTO.java
smartling-strings-api/src/main/java/com/smartling/api/strings/v2/pto/CreatedStringPTO.java
smartling-strings-api/src/main/java/com/smartling/api/strings/v2/pto/CreatedStringsListPTO.java
smartling-strings-api/src/main/java/com/smartling/api/strings/v2/pto/GetSourceStringsCommandPTO.java
smartling-strings-api/src/main/java/com/smartling/api/strings/v2/pto/ListCommandPTO.java
smartling-strings-api/src/main/java/com/smartling/api/strings/v2/pto/ProcessStatisticsPTO.java
smartling-strings-api/src/main/java/com/smartling/api/strings/v2/pto/SourceStringListPTO.java
smartling-strings-api/src/main/java/com/smartling/api/strings/v2/pto/SourceStringPTO.java
smartling-strings-api/src/main/java/com/smartling/api/strings/v2/pto/StringCreationPTO.java
smartling-strings-api/src/main/java/com/smartling/api/strings/v2/pto/StringKeyPTO.java
smartling-strings-api/src/main/java/com/smartling/api/strings/v2/pto/StringsCreationPTO.java
smartling-strings-api/src/main/java/com/smartling/api/strings/v2/pto/TranslationInternal.java
smartling-strings-api/src/main/java/com/smartling/api/strings/v2/pto/TranslationsCommandPTO.java
smartling-strings-api/src/main/java/com/smartling/api/strings/v2/pto/TranslationsPTO.java
smartling-strings-api/src/main/resources/com/smartling/api/strigns/v2/sdk-project.properties
smartling-strings-api/src/test/java/com/smartling/api/strings/v2/StringsApiTest.java

TCM-2046 Strings API collection not included in Java SDK

feat: Strings API v2

---

smartling-files-api/src/main/java/com/smartling/api/files/v2/pto/UploadFileResponse.java
smartling-files-api/src/test/java/com/smartling/api/files/v2/FilesApiIntTest.java

Add fileUri into response for files upload api. This fileUri will be used in repo connector to uploaded pdf files
[JIRA Ticket](https://bt.smartling.net/browse/REPO-578)
- use imperative, present …

feat: add fileUri to response for files upload api

---

smartling-jobs-api/src/main/java/com/smartling/api/jobs/v3/TranslationJobsApi.java
smartling-jobs-api/src/main/java/com/smartling/api/jobs/v3/pto/ProjectCustomFieldFilterPTO.java
smartling-jobs-api/src/test/java/com/smartling/api/jobs/v3/SampleApiResponses.java
smartling-jobs-api/src/test/java/com/smartling/api/jobs/v3/TranslationJobsApiTest.java

[JIRA Ticket](https://bt.smartling.net/browse/AEM-514)
Job API client allows to get custom fields assigned to a project

feat: get custom fields assigned to a project

---

smartling-jobs-api/src/main/java/com/smartling/api/jobs/v3/pto/TranslationJobResponsePTO.java

Added firstAuthorizedDate and lastAuthorizedDate fields
[JIRA Ticket](https://bt.smartling.net/browse/JOBS-4599)
- no dot (.) at …

JOBS-4599 add first authorized date and last authorized date

---

pom.xml
samrtling-api-test-utils/pom.xml
smartling-api-commons/pom.xml
smartling-api-commons/src/main/java/com/smartling/api/v2/client/ClientFactory.java
smartling-api-commons/src/main/java/com/smartling/api/v2/client/HttpClientConfiguration.java
smartling-api-commons/src/test/java/com/smartling/api/v2/client/ClientFactoryTest.java

Add Support of Custom SSL Context in HTTP clients.
[PPGIT-33](https://bt.smartling.net/browse/PPGIT-33),[PPGIT-49](https://bt.smartling.net/browse/PPGIT-49)
PayPal uses customized JVM with custom security providers, their default SSLContext is TLSv1.0 implementation.
In order to force using TLSv1.2 we need the ability to use custom SSL Context during httpClient configuring.
Solution: Added SSL context in HttpClientConfiguration and ClientFactory uses it if it is provided to construct httpClient.

feat: add support of custom ssl context in http clients

---

pom.xml
samrtling-api-test-utils/pom.xml
smartling-api-commons/pom.xml
smartling-api-sdk-all/pom.xml
smartling-attachments-api/pom.xml
smartling-contexts-api/pom.xml
smartling-files-api/pom.xml
smartling-files-api/src/main/java/com/smartling/api/files/v2/pto/DownloadMultipleTranslationsPTO.java
smartling-issues-api/pom.xml
smartling-job-batches-api/pom.xml
smartling-jobs-api/pom.xml
smartling-locales-api/pom.xml
smartling-projects-api/pom.xml
smartling-reports-api/pom.xml
smartling-strings-api/pom.xml

`FilesApi.downloadMultipleFileTranslations(...)` uses wrong parameter names: `fileUris & localeIds` instead of `fileUris[] & localeIds[]`.
[API Documentation](https://api-reference.smartling.com/\#tag/Files/operation/downloadMultipleTranslatedFiles)
[JIRA Ticket](https://bt.smartling.net/browse/DEVORTEX-3626)

DEVORTEX-3626 File API SDK - Wrong parameter names in download multiple file translations

---

smartling-files-api/src/main/java/com/smartling/api/files/v2/pto/DownloadMultipleTranslationsPTO.java

`FilesApi.downloadMultipleFileTranslations(...)` uses wrong parameter names: `fileUris & localeIds` instead of `fileUris[] & localeIds[]`.
[API Documentation](https://api-reference.smartling.com/#tag/Files/operation/downloadMultipleTranslatedFiles)
[Jira Ticket](https://bt.smartling.net/browse/DEVORTEX-3626)

fix: fix parameter names in download multiple file translations

---

smartling-api-commons/pom.xml
smartling-api-commons/src/main/resources/com/smartling/api/v2/authentication/sdk-project.properties
smartling-api-commons/src/test/java/com/smartling/api/v2/auth/AuthenticationIntegrationTest.java
smartling-file-translations-api/src/main/resources/com/smartling/api/filetranslations/v2/sdk-project.properties
smartling-file-translations-api/src/test/java/com/smartling/api/filetranslations/v2/FileTranslationsApiTest.java

warnings like: Could not initialize LibNameVersionHolder from properties: Properties file not found filename=sdk-project.properties

fix: properties not found warnings 

---

smartling-files-api/src/main/java/com/smartling/api/files/v2/FilesApi.java
smartling-files-api/src/main/java/com/smartling/api/files/v2/FilesApiFactory.java
smartling-files-api/src/main/java/com/smartling/api/files/v2/resteasy/ext/TranslatedFileMetadata.java
smartling-files-api/src/main/java/com/smartling/api/files/v2/resteasy/ext/TranslatedFileMultipart.java
smartling-files-api/src/main/java/com/smartling/api/files/v2/resteasy/ext/TranslatedFileMultipartReader.java
smartling-files-api/src/test/java/com/smartling/api/files/v2/FilesApiIntTest.java
smartling-files-api/src/test/java/com/smartling/api/files/v2/FilesApiTest.java
smartling-files-api/src/test/java/com/smartling/api/files/v2/resteasy/ext/TranslatedFileMultipartReaderTest.java

new method to download a translated file in the multipart/mixed format is added to Files API. the first part is file's body, the second part is json metadata (empty for now, we use it just to be sure that entire file was downloaded, maybe we will extend it with some additional data in the future)

feat: add support for multipart downloading of a translated file to Files API

---

smartling-accounts-api/src/main/java/com/smartling/api/accounts/v2/AccountsApi.java
smartling-api-commons/src/main/java/com/smartling/api/v2/client/ClientFactory.java
smartling-api-commons/src/main/java/com/smartling/api/v2/client/CloseClientInvocationHandler.java
smartling-api-commons/src/test/java/com/smartling/api/v2/client/CloseClientInvocationHandlerTest.java
smartling-attachments-api/src/main/java/com/smartling/api/attachments/v2/AttachmentsApi.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/ContextsApi.java
smartling-file-translations-api/src/main/java/com/smartling/api/filetranslations/v2/FileTranslationsApi.java
smartling-files-api/src/main/java/com/smartling/api/files/v2/FilesApi.java
smartling-glossary-api/src/main/java/com/smartling/api/glossary/v3/GlossaryApi.java
smartling-glossary-api/src/main/java/com/smartling/api/glossary/v3/components/GlossaryManagementApi.java
smartling-glossary-api/src/main/java/com/smartling/api/glossary/v3/components/entry/EntryManagementApi.java
smartling-glossary-api/src/main/java/com/smartling/api/glossary/v3/components/entry/auth/EntryAuthorizeForTranslationApi.java
smartling-glossary-api/src/main/java/com/smartling/api/glossary/v3/components/ie/ImportExportApi.java
smartling-glossary-api/src/main/java/com/smartling/api/glossary/v3/components/label/LabelManagementApi.java
smartling-issues-api/src/main/java/com/smartling/api/issues/v2/IssuesApi.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/util/FileUploadClientFactory.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/FileUploadProxy.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/JobBatchesApi.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/JobBatchesApiFactory.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/FileUploadProxy.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/JobBatchesApi.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/JobBatchesApiFactory.java
smartling-jobs-api/src/main/java/com/smartling/api/jobs/v3/TranslationJobsApi.java
smartling-locales-api/src/main/java/com/smartling/api/locales/v2/LocalesApi.java
smartling-projects-api/src/main/java/com/smartling/api/projects/v2/ProjectsApi.java
smartling-reports-api/src/main/java/com/smartling/api/reports/v3/ReportsApi.java
smartling-strings-api/src/main/java/com/smartling/api/strings/v2/StringsApi.java

[JIRA Ticket](https://smartling.atlassian.net/browse/AEM-854)
fix: APIs are auto-closeable. It allows user to release network resources used for making an API

fix: AEM-854: APIs are auto-closeable

---

smartling-attachments-api/src/main/java/com/smartling/api/attachments/v2/AttachmentsApi.java
smartling-attachments-api/src/test/java/com/smartling/api/attachments/v2/AttachmentsApiTest.java

DownloadAttachment endpoint.
[JIRA Ticket](https://smartling.atlassian.net/browse/CON-1574)

feat: add DownloadAttachment endpoint to Attachments API

---

smartling-api-commons/src/main/java/com/smartling/resteasy/ext/ExtendedMultipartFormWriter.java
smartling-api-commons/src/main/java/com/smartling/resteasy/ext/FileFormParam.java
smartling-api-commons/src/test/java/com/smartling/resteasy/ext/ExtendedMultipartFormWriterTest.java
smartling-api-commons/src/test/java/com/smartling/resteasy/ext/data/DummyMultipartApi.java
smartling-api-commons/src/test/java/com/smartling/resteasy/ext/data/FormWithFileFormParams.java
smartling-api-commons/src/test/java/com/smartling/resteasy/ext/integration/ExtendedMultipartFormWriterIntegrationTest.java
smartling-attachments-api/src/main/java/com/smartling/api/attachments/v2/pto/AttachmentUploadPTO.java
smartling-attachments-api/src/test/java/com/smartling/api/attachments/v2/AttachmentsApiTest.java

[WKFT-138](https://smartling.atlassian.net/browse/WKFT-138)
- Extend RESTEasy's MultipartFormAnnotationWriter to pass filename in Content-Disposition header.
- Pass correct filename on attachment upload
[WKFT-138]: https://smartling.atlassian.net/browse/WKFT-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: pass correct filename on attachment upload

---

smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/pto/ContentAssignmentPTO.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/pto/WorkflowPTO.java
smartling-job-batches-api/src/test/java/com/smartling/api/jobbatches/v2/JobBatchesApiTest.java

[JIRA Ticket](https://bt.smartling.net/browse/{jira_id_here})

feat: con 592 update job batches v2 endpoint

---

pom.xml
smartling-mt-router-api/pom.xml
smartling-mt-router-api/src/main/java/com/smartling/api/mtrouter/v2/MtRouterApi.java
smartling-mt-router-api/src/main/java/com/smartling/api/mtrouter/v2/MtRouterApiFactory.java
smartling-mt-router-api/src/main/java/com/smartling/api/mtrouter/v2/pto/ErrorPTO.java
smartling-mt-router-api/src/main/java/com/smartling/api/mtrouter/v2/pto/GenerateAccountTranslationCommandPTO.java
smartling-mt-router-api/src/main/java/com/smartling/api/mtrouter/v2/pto/SourceStringCommandPTO.java
smartling-mt-router-api/src/main/java/com/smartling/api/mtrouter/v2/pto/TranslationPTO.java
smartling-mt-router-api/src/main/resources/com/smartling/api/mtrouter/v2/sdk-project.properties
smartling-mt-router-api/src/test/java/com/smartling/api/mtrouter/v2/MtRouterApiTest.java
smartling-mt-router-api/src/test/java/com/smartling/api/mtrouter/v2/SampleApiResponses.java

Add mt-router api
[JIRA Ticket](https://smartling.atlassian.net/browse/JOBS-8225)

Add mt-router api

---

smartling-accounts-api/pom.xml
smartling-attachments-api/pom.xml
smartling-contexts-api/pom.xml
smartling-issues-api/pom.xml
smartling-jobs-api/pom.xml
smartling-locales-api/pom.xml
smartling-mt-router-api/pom.xml
smartling-projects-api/pom.xml
smartling-reports-api/pom.xml
smartling-strings-api/pom.xml

Generated sdk-project.properties, which is included within sdk jar, for many sdks contains unextended project variables.
When one uses sdk, by default properties taken from sdk-project.properties are used to generate User-agent header which leads to user-agent header looking like this in our apigateway log:
```2025-06-10 11:15:47:682 +0000 - [INFO] [http-nio-8443-exec-431] (RequestSummaryFilter.java:run:159) rid=002a673a-966e-4ec6-a0de-442b8c7e52fa#tqdm 	[MAINLOG] Request finished, status_code=200, service_id=JOBS-SERVICE, total_time=36, auth_filter_time=29, user=service+email-notifications@smartling.com, method=POST, url="https://api.smartling.com/jobs-admin-api/v3/projects/f67df5d74/find-jobs-by-content", service_uri="/jobs-admin-api/v3/projects/f67df5d74/find-jobs-by-content", …
```

fix: fix sdk-project.properties project variables substitution

---

smartling-glossary-api/src/main/java/com/smartling/api/glossary/v3/pto/entry/GlossaryEntryBaseResponsePTO.java
smartling-glossary-api/src/test/java/com/smartling/api/glossary/v3/components/entry/EntryManagementApiTest.java

[JOBS-8469](https://smartling.atlassian.net/browse/JOBS-8469)
Add Glossary Entry suggestion status
- use imperative, present tense: …

feat: add Glossary Entry suggestion status

---

.circleci/release.sh
.circleci/settings.xml
pom.xml

Tested in https://github.com/Smartling/java-api-sdk/pull/121
Job: https://app.circleci.com/pipelines/github/Smartling/java-api-sdk/461/workflows/761ea226-8811-4d7d-9e88-a8ddaa9c4943
https://central.sonatype.com/publishing/deployments:

feat: deploy to Central Publisher Portal instead of sonatype OSSRH

---

smartling-strings-api/src/main/java/com/smartling/api/strings/v2/StringsApi.java
smartling-strings-api/src/test/java/com/smartling/api/strings/v2/StringsApiTest.java

[TCM-6005](https://bt.smartling.net/browse/TCM-6005)
[TCM-6005]: https://smartling.atlassian.net/browse/TCM-6005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add Strings API POST requests
