.github/CODEOWNERS
pom.xml
smartling-api-sdk-all/pom.xml
smartling-api-sdk-all/src/main/java/com/smartling/api/sdk/SmartlingApi.java
smartling-api-sdk-all/src/main/java/com/smartling/api/sdk/SmartlingApiImpl.java
smartling-projects-api/pom.xml
smartling-projects-api/src/main/java/com/smartling/api/projects/v2/ProjectsApi.java
smartling-projects-api/src/main/java/com/smartling/api/projects/v2/ProjectsApiFactory.java
smartling-projects-api/src/main/java/com/smartling/api/projects/v2/pto/LocaleDetailsPTO.java
smartling-projects-api/src/main/java/com/smartling/api/projects/v2/pto/ProjectDetailsPTO.java
smartling-projects-api/src/main/resources/com/smartling/api/projects/v2/sdk-project.properties
smartling-projects-api/src/test/java/com/smartling/api/projects/v2/ProjectsApiFactoryTest.java
smartling-projects-api/src/test/java/com/smartling/api/projects/v2/ProjectsApiTest.java

feat: add Projects API
[CON-594](https://bt.smartling.net/browse/CON-594) Made Projects API a part of public API

feat: add Projects API

---

smartling-files-api/src/main/java/com/smartling/api/files/v2/pto/FileType.java

Add PDF file type
[JIRA Ticket](https://bt.smartling.net/browse/JOBSBATCH-140)
- no dot (.) at the end

feat: add PDF file type

---

smartling-files-api/src/main/java/com/smartling/api/files/v2/pto/FileType.java

Add FLUENT file format to sdk. 
[JIRA Ticket](https://bt.smartling.net/browse/REPO-568)
Details about FLUET format https://github.com/projectfluent/fluent/wiki
- use imperative, present tense: …

REPO-568 Fluent Parser Testing and Changes

---

smartling-files-api/src/main/java/com/smartling/api/files/v2/pto/FileType.java

Add FLUENT file format to sdk.
[JIRA Ticket](https://bt.smartling.net/browse/REPO-568)
Details about FLUET format https://github.com/projectfluent/fluent/wiki
- use imperative, present tense: …

Repo 568 repo connector fluent parser support

---

smartling-files-api/src/main/java/com/smartling/api/files/v2/pto/FileType.java

Add FLUENT file format to sdk.
[JIRA Ticket](https://bt.smartling.net/browse/REPO-568)
Details about FLUET format https://github.com/projectfluent/fluent/wiki
- use imperative, present tense: …

feat: add FLUENT format

---

smartling-files-api/src/main/java/com/smartling/api/files/v2/FilesApiFactory.java

Add client's libNameHolder to files api sdk
[JIRA Ticket](https://bt.smartling.net/browse/REPO-575)
- no dot (.) at the end

fix: add client's libNameHolder to files api sdk

---

smartling-jobs-api/src/main/java/com/smartling/api/jobs/v3/TranslationJobsApi.java
smartling-jobs-api/src/main/java/com/smartling/api/jobs/v3/pto/HashcodesByLocalePTO.java
smartling-jobs-api/src/main/java/com/smartling/api/jobs/v3/pto/LocaleHashcodePairPTO.java
smartling-jobs-api/src/main/java/com/smartling/api/jobs/v3/pto/TranslationJobFindByLocalesAndHashcodesCommandPTO.java
smartling-jobs-api/src/main/java/com/smartling/api/jobs/v3/pto/TranslationJobFoundByStringsAndLocalesResponsePTO.java
smartling-jobs-api/src/test/java/com/smartling/api/jobs/v3/SampleApiResponses.java
smartling-jobs-api/src/test/java/com/smartling/api/jobs/v3/TranslationJobsApiTest.java

Moved find by hashcode and locale from internal api into public
[JIRA Ticket](https://bt.smartling.net/browse/JOBS-3477)

feat: add find by hashcode/locale and get content to public sdk

---

example/FilesApiExample.java

docs: Added FilesApi example

---

smartling-attachments-api/src/test/java/com/smartling/api/attachments/v2/AttachmentsApiTest.java

[JIRA Ticket](https://bt.smartling.net/browse/{jira_id_here})
- no …

feat: add attachments API

---

smartling-api-commons/src/main/java/com/smartling/api/v2/response/RestApiResponse.java

[JIRA Ticket](https://bt.smartling.net/browse/{jira_id_here})
- no …

fix: Fix RestApiResponse deserialization

---

pom.xml
smartling-api-commons/src/main/java/com/smartling/api/v2/client/unmarshal/RestApiContextResolver.java

[JIRA Ticket](https://bt.smartling.net/browse/{jira_id_here})
- no …

feat: Add support for Kotlin data classes deserialization

---

smartling-api-commons/src/main/java/com/smartling/api/v2/client/unmarshal/RestApiResponseReaderInterceptor.java
smartling-api-commons/src/test/java/com/smartling/api/v2/client/unmarshal/RestApiResponseReaderInterceptorTest.java

[JIRA Ticket](https://bt.smartling.net/browse/CON-958)
Read response (both: data and error) as a string

fix: read response as a string

---

pom.xml
smartling-contexts-api/pom.xml
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/ContextsApi.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/ContextsApiFactory.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/BatchBindingPTO.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/BatchBindingRequestPTO.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/BatchDeleteBindingsRequestPTO.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/BindingPTO.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/BindingRequestPTO.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/BindingsRequestPTO.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/ContextPTO.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/ContextUploadAndMatchPTO.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/ContextUploadPTO.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/CoordinatesPTO.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/MatchIdPTO.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/MatchRequestPTO.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/MatchStatusPTO.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/PaginatedListResponse.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/TimecodePTO.java
smartling-contexts-api/src/main/resources/com/smartling/api/contexts/v2/sdk-project.properties
smartling-contexts-api/src/test/java/com/smartling/api/contexts/v2/ContextsApiTest.java

[JIRA Ticket](https://bt.smartling.net/browse/DELTA-805)
`feat: add Contexts API`
Add Contexts API

DELTA-805 add contexts sdk

---

smartling-contexts-api/pom.xml

[JIRA Ticket](https://bt.smartling.net/browse/DELTA-805)
`feat: add Context API`

delta-805 update version

---

.github/CODEOWNERS
smartling-api-sdk-all/pom.xml
smartling-api-sdk-all/src/main/java/com/smartling/api/sdk/SmartlingApi.java
smartling-api-sdk-all/src/main/java/com/smartling/api/sdk/SmartlingApiImpl.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/ContextsApi.java

[JIRA Ticket](https://bt.smartling.net/browse/DELTA-805)
- no dot …

fix: change return type for deleteBindings endpoint

---

smartling-api-commons/src/main/java/com/smartling/api/v2/client/HttpHeadersFilter.java
smartling-api-commons/src/test/java/com/smartling/api/v2/client/HttpHeadersFilterTest.java

[JIRA Ticket](https://bt.smartling.net/browse/DELTA-1284)
`feat: add HttpHeadersFilter`

delta-1284 add http headers filter

---

smartling-files-api/src/main/java/com/smartling/api/files/v2/pto/FileType.java

Add support for Docm file type format

feat: Add support for Docm file type format

---

.github/CODEOWNERS
pom.xml
smartling-api-sdk-all/pom.xml
smartling-api-sdk-all/src/main/java/com/smartling/api/sdk/SmartlingApi.java
smartling-api-sdk-all/src/main/java/com/smartling/api/sdk/SmartlingApiImpl.java
smartling-reports-api/pom.xml
smartling-reports-api/src/main/java/com/smartling/api/reports/v3/ReportsApi.java
smartling-reports-api/src/main/java/com/smartling/api/reports/v3/ReportsApiFactory.java
smartling-reports-api/src/main/java/com/smartling/api/reports/v3/pto/WordCountReportCommandPTO.java
smartling-reports-api/src/main/java/com/smartling/api/reports/v3/pto/WordCountResponsePTO.java
smartling-reports-api/src/main/resources/com/smartling/api/reports/v3/sdk-project.properties
smartling-reports-api/src/test/java/com/smartling/api/reports/v3/ReportsApiIntTest.java
smartling-reports-api/src/test/java/com/smartling/api/reports/v3/ReportsApiTest.java

[ Word Count API - update old TMS word count endpoints to proxy requests to reports service](https://bt.smartling.net/browse/DT-2341)
feat: (Word count report public sdk)

feat: (Word count report public sdk)

---

smartling-jobs-api/src/main/java/com/smartling/api/jobs/v3/pto/TranslationJobAddFileCommandPTO.java
smartling-jobs-api/src/test/java/com/smartling/api/jobs/v3/TranslationJobsApiTest.java

Removed moveEnabled parameter from addFileToTranslationJob method
[JIRA Ticket](https://bt.smartling.net/browse/JOBS-4746)
- no …

JOBS-4746 remove moveEnabled

---

smartling-api-commons/pom.xml
smartling-api-commons/src/main/java/com/smartling/api/v2/client/ExceptionDecoratorInvocationHandler.java
smartling-api-commons/src/main/java/com/smartling/api/v2/client/exception/RestApiExceptionHandler.java
smartling-api-commons/src/main/java/com/smartling/api/v2/client/exception/RestApiRuntimeException.java
smartling-api-commons/src/main/java/com/smartling/api/v2/client/exception/server/DetailedErrorMessage.java
smartling-api-commons/src/test/java/com/smartling/api/v2/client/ExceptionDecoratorInvocationHandlerTest.java
smartling-api-commons/src/test/java/com/smartling/api/v2/client/exception/RestApiExceptionHandlerTest.java
smartling-files-api/src/main/java/com/smartling/api/files/v2/FilesApi.java

this change will allow to add in declarative manner needed invocation params to our Rest Api error messages.

feat: MTCH-155: include details in Rest Api error messages

---

smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/pto/BatchItemPTO.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/pto/BatchItemStatus.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/pto/BatchStatus.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/pto/BatchStatusResponsePTO.java
smartling-job-batches-api/src/test/java/com/smartling/api/jobbatches/v2/JobBatchesApiTest.java

make batch and batch item statuses are enums
[JOBSBATCH-194](https://bt.smartling.net/browse/JOBSBATCH-194)

feat: make batch and batch item statuses are enums

---

smartling-files-api/src/main/java/com/smartling/api/files/v2/pto/FileType.java

Add support for XLSX_TEMPLATE file format type in java sdk
[JIRA Ticket](https://bt.smartling.net/browse/TCM-3841)

feat: add support for XLSX_TEMPLATE file type

---

smartling-files-api/src/main/java/com/smartling/api/files/v2/pto/FileType.java

https://bt.smartling.net/browse/CLDSTRG-116

feat: add svg and vtt file types

---

smartling-files-api/src/main/java/com/smartling/api/files/v2/pto/FileType.java

https://bt.smartling.net/browse/CLDSTRG-119

feat: extend file types

---

smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v1/pto/FileUploadPTO.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/pto/FileUploadPTO.java

https://bt.smartling.net/browse/JOBSBATCH-199

feat: extend file upload pto

---

smartling-api-commons/src/main/java/com/smartling/api/v2/client/ClientFactory.java
smartling-api-commons/src/main/java/com/smartling/api/v2/client/graphql/AbstractGraphQlModel.java
smartling-api-commons/src/main/java/com/smartling/api/v2/client/graphql/GraphQlClientFactory.java
smartling-api-commons/src/main/java/com/smartling/api/v2/client/graphql/GraphQlResponseReaderInterceptor.java
smartling-api-commons/src/main/java/com/smartling/api/v2/client/graphql/GraphQlSerializer.java
smartling-api-commons/src/main/java/com/smartling/api/v2/client/unmarshal/RestApiContextResolver.java
smartling-api-commons/src/main/java/com/smartling/api/v2/client/unmarshal/RestApiResponseReaderInterceptor.java
smartling-api-commons/src/test/java/com/smartling/api/v2/client/graphql/GraphQlClientFactoryTest.java
smartling-api-commons/src/test/java/com/smartling/api/v2/client/unmarshal/RestApiContextResolverTest.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/util/FileUploadClientFactory.java

Add a common GraphQL support
[JIRA Ticket](https://bt.smartling.net/browse/JOBS-5501)
- no dot (.) at the end

feat: add common GraphQL support

---

.github/CODEOWNERS
pom.xml
smartling-accounts-api/pom.xml
smartling-accounts-api/src/main/java/com/smartling/api/accounts/v2/AccountsApi.java
smartling-accounts-api/src/main/java/com/smartling/api/accounts/v2/AccountsApiFactory.java
smartling-accounts-api/src/main/java/com/smartling/api/accounts/v2/pto/GetProjectsListPTO.java
smartling-accounts-api/src/main/java/com/smartling/api/accounts/v2/pto/PaginationPTO.java
smartling-accounts-api/src/main/java/com/smartling/api/accounts/v2/pto/ProjectDetailsPTO.java
smartling-accounts-api/src/main/resources/com/smartling/api/accounts/v2/sdk-project.properties
smartling-accounts-api/src/test/java/com/smartling/api/accounts/v2/AccountsApiTest.java
smartling-accounts-api/src/test/resources/projectsByAccountResponse.json
smartling-api-sdk-all/pom.xml
smartling-api-sdk-all/src/main/java/com/smartling/api/sdk/SmartlingApi.java
smartling-api-sdk-all/src/main/java/com/smartling/api/sdk/SmartlingApiImpl.java

Add Accounts API.
[CON-1321](https://bt.smartling.net/browse/CON-1321) Return list of active integrations for account

feat: add Accounts API

---

smartling-accounts-api/pom.xml
smartling-api-sdk-all/pom.xml

`feat: add Accounts API`
[CON-1321](https://bt.smartling.net/browse/CON-1321) Return list of active integrations for account

CON-1321 update version

---

smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/FileUploadProxy.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/JobBatchesApi.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/pto/CreateJobRequestPTO.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/pto/CreateJobResponsePTO.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/pto/JobCreationMode.java
smartling-job-batches-api/src/main/java/com/smartling/api/jobbatches/v2/pto/JobCreationSalt.java
smartling-job-batches-api/src/test/java/com/smartling/api/jobbatches/v2/JobBatchesApiTest.java

CreateJob endpoint.
[JIRA Ticket](https://bt.smartling.net/browse/CON-1534)

feat: add CreateJob endpoint to Job Batches API

---

smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/BindingPTO.java
smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/BindingRequestPTO.java
smartling-contexts-api/src/test/java/com/smartling/api/contexts/v2/ContextsApiTest.java

Added possibility to create pdf bindings 
[JIRA Ticket](https://bt.smartling.net/browse/DELTA-2868)
Extended createBindings and listBindings endpoints to support bindings with Coordinates and Page number that are required by PDF contexts

feat: pdf bindings support

---

smartling-files-api/src/test/java/com/smartling/api/files/v2/FilesApiTest.java

DEVORTEX-5264 Implement recently-published api

feat: Implement recently-published api (#112)
